spring:
  application:
    name: helloworld-example
  config:
    import:
      - optional:nacos:cipher-kms-aes-256-encrypted-config.properties?group=DEFAULT_GROUP&refreshEnabled=true
  nacos:
    config:
      server-addr: ${NACOS_SERVER_ADDR}
      access-key: ${NACOS_ACCESS_KEY}
      secret-key: ${NACOS_SECRET_KEY}
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
